# Generated by Django 4.2.16 on 2024-10-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(max_length=50)),
                ('pcap_file', models.FileField(upload_to='pcap_files/')),
                ('ip_source', models.GenericIPAddressField()),
                ('ip_destination', models.GenericIPAddressField()),
                ('port_source', models.IntegerField()),
                ('port_destination', models.IntegerField()),
                ('pid_sender', models.IntegerField()),
                ('time_sent', models.DateTimeField()),
                ('time_received', models.DateTimeField()),
                ('capture_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('os_info', models.TextField()),
                ('kernel_version', models.CharField(max_length=50)),
                ('architecture', models.CharField(max_length=20)),
                ('users', models.TextField()),
                ('all_users', models.TextField()),
                ('ip_addresses', models.TextField()),
                ('open_ports', models.TextField()),
                ('active_connections', models.TextField()),
                ('processes', models.TextField()),
                ('cpu_info', models.TextField()),
                ('memory_info', models.TextField()),
                ('disk_usage', models.TextField()),
                ('usb_devices', models.TextField()),
                ('env_vars', models.TextField()),
                ('system_time', models.DateTimeField()),
                ('installed_packages', models.TextField()),
                ('active_services', models.TextField()),
            ],
        ),
    ]
