# Generated by Django 4.2.16 on 2024-10-17 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_remove_systemdata_active_connections_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemdata',
            name='system_time',
        ),
    ]
