# Generated by Django 4.2.16 on 2024-10-18 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_systemdata_system_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networktraffic',
            name='pcap_file',
        ),
    ]
