# Generated by Django 4.2.16 on 2024-10-18 05:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_remove_networktraffic_pcap_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networktraffic',
            name='time_received',
        ),
        migrations.RemoveField(
            model_name='networktraffic',
            name='time_sent',
        ),
        migrations.AddField(
            model_name='networktraffic',
            name='capture_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='networktraffic',
            name='capture_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='networktraffic',
            name='pid_sender',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
